### ISSUE TITLE
freak attack vulnerable

### ISSUE THREAD

**Issue by ka223** [Anasthase/TintBrowser#84]
The browser is freak attack vulnerable.

http://www.directupload.net/file/u/58407/icfipveo_png.htm
http://www.directupload.net/file/u/58407/t3a7hz73_png.htm

**Comment by gravgun** [comment]
Bullshit. Android is at fault, not Tint.

**Comment by f1vefour** [comment]
You mean webview, not Android.

**Comment by ka223** [comment]
ok, I did not know that
